/**
 * THE ONE-TIME PRODUCTS — Genesis's own listing (28 Sep 2026), verbatim:
 * four per division for AI Labs, Studios and Brand & Design, three for
 * Influence. Fifteen in all. They replace every add-on and every earlier
 * one-time product (the AI Content Starter, the Content Shoot packages, the
 * one-time projects rail); the memberships are untouched and live with each
 * division in lib/verticals.
 *
 * Fixed-price products end in "Buy Now" and "+ Add to Cart". The one whose
 * price depends on creators, scope, location or requirements — Influencer
 * Campaign Management — ends in "Book a 15-min Call" and is never in the
 * cart.
 *
 * `price` is the figure Genesis gave (₹24,999 → 24999), shown the house way
 * ("₹24,999/-") by lib/money. `inPerson` marks a product that needs a
 * physical shoot by a Genesis crew — Mumbai only, for now (lib/regions).
 */

import type { VerticalKey } from "./verticals/types";

export type OneTimeProduct = {
  vertical: VerticalKey;
  index: string;
  name: string;
  /** What it does for the buyer — the line under the name. */
  pitch: string;
  /** Who it is for ("For:" in Genesis's sheet), in full. */
  audience?: string;
  /** The same, split for the pop-up's pills: who, as short tags… */
  audienceTags?: readonly string[];
  /** …and what they need, the rest of the sentence. */
  audienceNeed?: string;
  includes: readonly string[];
  /** The four steps from buying to delivery, as the pop-up shows them. */
  process?: readonly string[];
  /** A line before the list of what Genesis needs from the client. */
  requirementsIntro?: string;
  /** What Genesis needs from the brand or client to start. */
  requirements?: readonly string[];
  /** Extras that can be added, each with its price or "quoted separately". */
  addOns?: readonly string[];
  /** Rupees, as sold. Absent where the price is quoted (`priceLabel`). */
  price?: number;
  priceLabel?: string;
  /** A line (or two) under the list — "No influencer posting included." */
  note?: string;
  /** The product's own terms, paragraph by paragraph. */
  terms?: readonly string[];
  /** Needs a physical shoot by a Genesis crew — Mumbai only, for now. */
  inPerson?: boolean;
  /** "buy": Buy Now + Add to Cart. "call": Book a 15-min Call. */
  cta: "buy" | "call";
};

/*
  REPLACED FROM GENESIS'S SHEET, 3 Oct 2026 ("Website products and
  subscriptions.xlsx", Pay-per-project tab): names, prices, what each does,
  who it is for, everything included, the four-step process, what Genesis
  needs from the client, add-ons, notes and each product's terms — verbatim.
  The sheet's vendor-cost column is internal and is not carried here, nor
  are its notes to the developer ("Website control: + Add adaptation",
  "Duration extension, website pricing slider…"), which describe controls
  still to be built.
*/
export const products: readonly OneTimeProduct[] = [
  /* ------------------------------------------------------------ AI Labs */
  {
    vertical: "ai-labs",
    index: "01",
    name: "Build Your AI Avatar Clone",
    price: 24999,
    pitch: "Turn yourself, your founder or spokesperson into a reusable Digital AI Avatar for social media, founder-led content and product explainer videos, so you can create new videos featuring you without organising a fresh shoot every time.",
    audience: "Founders, artists, creators, influencers, celebrities, advocates, doctors and other busy professionals who want to stay visible consistently without making time for frequent shoots.",
    audienceTags: ["Founders", "Artists", "Creators", "Influencers", "Celebrities", "Advocates", "Doctors", "Other busy professionals"],
    audienceNeed: "who want to stay visible consistently without making time for frequent shoots.",
    includes: [
      "1 Realistic Digital AI Avatar, one-time setup",
      "3 Standard AI Videos",
      "Standard AI Video format: AI-generated video + licensed stock footage / B-roll + AI-generated or supplied still-image sequences",
      "1–3 AI-generated motion clips per video (max. 3), approx. 5–7 sec each",
      "Standard AI Voice Clone",
      "Avatar training & setup",
      "1080p final video delivery",
      "1 consolidated revision round per included video",
      "Reusable avatar ready for future founder-led, social media and product explainer content",
    ],
    process: [
      "Purchase",
      "Upload photos + voice",
      "We build your avatar + 3 videos",
      "Review, approve & reuse",
    ],
    requirementsIntro: "We’ll share a recording guide and Drive upload link. Please provide:",
    requirements: [
      "30 minutes of clean voice recordings",
      "Approx. 100 clear reference photographs",
      "Written consent from the person being cloned",
      "Brand links, logos, colours and previous content references (optional but recommended)",
    ],
    addOns: [
      "AI Avatar Creation: ₹14,999/- per avatar",
      "Advanced AI Voice Clone: ₹4,499/-",
      "Advanced Video Edit: ₹14,999/- per video",
      "Post-final edit changes: ₹5,499/- per video",
      "AI video regeneration: ₹999/- per 5–10 sec generation",
      "Additional languages / versions: quoted separately",
      "Add an adaptation / alternate aspect-ratio version: quoted separately",
    ],
    note: "One-time avatar setup. Once created, the avatar can be reused for future Genesis AI content without repeating the full setup process, subject to platform/model requirements.\n\nAI production follows the approval workflow in Terms & glossary: script lock → Draft 1 image/timeline approval → AI video generation → Draft 2 final delivery.",
    terms: [
      "100% advance payment is required before production begins.",
      "Written consent is required for any real person whose likeness or voice is cloned. Script/brief approval locks the scope. Draft 1 covers AI images/keyframes + video timeline; video generation starts only after those visuals are approved. 1 consolidated revision round per included video is allowed at Draft 1. Draft 2 is final delivery in 1080p.",
      "Post-final edit-only changes: ₹5,499 + GST/video. Fresh AI video regeneration: ₹999 + GST per 5–10 sec generated clip. Fresh AI image generation, new scripts/concepts, added duration or scope changes are quoted separately. AI output may vary by generation and source quality. Raw models/model access, prompts and working files are not included unless agreed in writing.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    cta: "buy",
  },
  {
    vertical: "ai-labs",
    index: "02",
    name: "AI Video Campaign Content Pack",
    price: 39999,
    pitch: "Turn your product, service, campaign or idea into 4 ready-to-publish AI videos, created from concept to final delivery without organising a traditional production shoot.",
    audience: "Brands, startups and businesses that need fast, high-quality video content for product explainers, launches, social media, AI-led campaigns, events and promotions.",
    audienceTags: ["Brands", "Startups", "Businesses"],
    audienceNeed: "that need fast, high-quality video content for product explainers, launches, social media, AI-led campaigns, events and promotions.",
    includes: [
      "4 Standard AI Videos",
      "Up to 30 sec each",
      "Standard AI Video format: AI-generated video + licensed stock footage / B-roll + AI-generated or supplied still-image sequences",
      "1–3 AI-generated motion clips per video (max. 3), approx. 5–7 sec each",
      "Ideation & scriptwriting",
      "AI visual production",
      "Basic AI voiceover",
      "Background music",
      "Captions & supers",
      "Brand styling",
      "Product / service integration",
      "9:16 or 16:9 delivery",
      "1080p final export",
      "1 consolidated revision round per video",
    ],
    process: [
      "Purchase",
      "Share brief + brand assets",
      "Approve script + visuals",
      "We generate, edit & deliver",
    ],
    requirements: [
      "Campaign / content brief",
      "Brand guidelines and logo files",
      "Product or service information",
      "Website / social links",
      "Reference videos or mood references",
      "Product images, screenshots or existing brand assets",
      "Mandatory claims / disclaimers, if applicable",
    ],
    addOns: [
      "AI Avatar Creation: ₹14,999/- per avatar",
      "Advanced AI Voice Clone: ₹4,499/-",
      "Advanced Video Edit: ₹14,999/- per video",
      "Post-final edit changes: ₹5,499/- per video",
      "AI video regeneration: ₹999/- per 5–10 sec generation",
      "Additional language / aspect-ratio versions: quoted separately",
      "Add an adaptation / alternate cut or aspect-ratio version: quoted separately",
    ],
    note: "AI production follows the approval workflow in Terms & glossary: script lock → Draft 1 image/timeline approval → AI video generation → Draft 2 final delivery.\n\nFinal output depends on the complexity of the concept and assets provided. Advanced animation, complex AI scenes, fresh generations or changes to an approved script/concept may be scoped and charged separately.",
    terms: [
      "100% advance payment is required before production begins.",
      "Script/brief approval locks the core message, duration and concept. Draft 1 covers AI images/keyframes + proposed video timeline/storyboard; AI video generation begins only after visual approval. 1 consolidated revision round per video is included at Draft 1. Draft 2 is final delivery in 1080p.",
      "Standard AI Videos use a mix of AI-generated motion clips, licensed stock footage / B-roll and AI-generated or supplied still-image sequences. Each Standard AI Video includes 1–3 AI-generated motion clips (maximum 3), approximately 5–7 seconds each.",
      "Post-final edit-only changes: ₹5,499 + GST/video. Fresh AI video regeneration: ₹999 + GST per 5–10 sec generated clip. Fresh AI image generation, new scripts/concepts, extra duration or scope changes are quoted separately. Any real-person AI requires written consent.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    cta: "buy",
  },
  {
    vertical: "ai-labs",
    index: "03",
    name: "AI Product Explainer + Advance Motion Graphics",
    price: 44999,
    pitch: "Explain a product, service or feature through a polished AI-powered explainer that makes complex information easier to understand and more engaging to watch.",
    audience: "SaaS, tech, BFSI, healthcare, education, D2C and product-led businesses launching or explaining a product, feature, process or service.",
    audienceTags: ["SaaS", "Tech", "BFSI", "Healthcare", "Education", "D2C", "Product-led businesses"],
    audienceNeed: "launching or explaining a product, feature, process or service.",
    includes: [
      "1 AI Product Explainer Video",
      "Up to 45 seconds",
      "Concept development & scriptwriting",
      "Storyboard / visual direction",
      "AI-generated visuals + stock / B-roll where required",
      "Product, UI or brand integration",
      "AI voiceover",
      "Motion graphics & animation",
      "Music & sound treatment",
      "Captions & supers",
      "16:9 or 9:16 master in 1080p",
      "1 consolidated revision round",
    ],
    process: [
      "Purchase",
      "Share product + brand inputs",
      "Approve script + storyboard",
      "We animate, edit & deliver",
    ],
    requirements: [
      "Product / service brief",
      "Website, app or demo access where relevant",
      "Product screenshots, UI files, packshots or reference assets",
      "Brand guidelines and logo files",
      "Key features / messages to highlight",
      "Approved claims, data and mandatory disclaimers",
      "Reference videos or visual direction",
    ],
    addOns: [
      "AI Avatar Creation: ₹14,999/- per avatar",
      "Additional aspect-ratio adaptation (second master): quoted separately",
      "Advanced AI Voice Clone: ₹4,499/-",
      "Additional language / localisation: quoted separately",
      "Post-final edit changes: ₹5,499/- per video",
      "AI video regeneration: ₹999/- per 5–10 sec generation",
      "Additional runtime / versions: quoted separately",
      "Add an adaptation: quoted separately",
    ],
    terms: [
      "100% advance payment is required before production begins.",
      "The approved script, concept, duration and brand direction become the production lock. AI images/keyframes are approved before full video generation begins. The product includes 1 consolidated revision round within the approved scope. Fresh AI generations, new concepts, script changes, additional duration or advanced edits are chargeable. Final delivery is 1080p in the agreed format.",
      "AI output is dependent on source quality and third-party AI tools; exact visual or motion consistency cannot be guaranteed in every generation.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    cta: "buy",
  },
  {
    vertical: "ai-labs",
    index: "04",
    name: "AI Campaign Film + Advanced Motion Graphic Video",
    price: 67999,
    pitch: "Create a premium AI-produced hero film around one campaign idea, designed to deliver a stronger visual story without the cost and logistics of a conventional large-scale shoot.",
    audience: "Brands, agencies and marketing teams launching campaigns, products, brand films, festive communication or high-impact digital moments.",
    audienceTags: ["Brands", "Agencies", "Marketing teams"],
    audienceNeed: "launching campaigns, products, brand films, festive communication or high-impact digital moments.",
    includes: [
      "1 Hero AI Campaign Film",
      "Up to 45 sec",
      "Creative concept & scriptwriting",
      "Moodboard / storyboard direction",
      "Advanced AI production",
      "Custom AI-generated scenes",
      "Product / brand integration",
      "Advanced motion & compositing",
      "Voiceover",
      "Music & sound design",
      "Captions & supers",
      "16:9 master in 1080p",
      "1 consolidated revision round",
    ],
    process: [
      "Purchase",
      "Share campaign brief",
      "Approve concept + storyboard",
      "We produce, refine & deliver",
    ],
    requirements: [
      "Campaign brief and objective",
      "Target audience and key message",
      "Brand guidelines, logos and mandatory elements",
      "Product packshots / references / existing campaign assets",
      "Approved claims and disclaimers",
      "Reference films / visual direction",
      "One client-side decision maker for consolidated approvals",
    ],
    addOns: [
      "AI Avatar Creation: ₹14,999/- per avatar",
      "9:16 / 1:1 cutdowns: quoted separately",
      "Advanced AI Voice Clone: ₹4,499/-",
      "Additional languages / localisation: quoted separately",
      "Additional AI video generation: ₹999/- per 5–10 sec generation",
      "Post-final edit changes: ₹5,499/- per video",
      "Extra scenes, versions or runtime: quoted separately",
      "Add an adaptation / alternate cut or aspect-ratio version: quoted separately",
    ],
    terms: [
      "100% advance payment is required before production begins.",
      "The approved concept, script, duration and campaign direction become the production lock. AI scenes/keyframes are approved before final generation wherever applicable. The 2 included revision rounds apply within the approved concept; new concepts, significant scene changes, fresh generations, extra duration or added deliverables are chargeable and may extend the timeline. Final delivery is 1080p in the agreed format.",
      "AI output is dependent on source quality and third-party AI tools; exact visual or motion consistency cannot be guaranteed in every generation.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    cta: "buy",
  },
  /* ------------------------------------------------------------ Studios */
  {
    vertical: "studios",
    index: "01",
    name: "Reel Editing Pack",
    price: 24999,
    pitch: "Turn your existing footage into polished, branded short-form content that is ready for social media without organising another shoot.",
    audience: "Brands, founders, creators, teams and businesses that already have footage but need consistent, professionally edited reels.",
    audienceTags: ["Brands", "Founders", "Creators", "Teams", "Businesses"],
    audienceNeed: "that already have footage but need consistent, professionally edited reels.",
    includes: [
      "Up to 7 edited reels",
      "Client-supplied footage",
      "Up to 30 sec each",
      "Footage selection & assembly",
      "Captions",
      "Brand styling",
      "Basic motion graphics",
      "Licensed / copyright-safe background music",
      "Basic colour correction",
      "Basic audio clean-up",
      "Primary 9:16 exports in 1080p",
      "1 revision per reel",
    ],
    process: [
      "Purchase",
      "Upload footage + brief",
      "We edit up to 7 reels",
      "Review & receive final exports",
    ],
    requirements: [
      "Organised raw footage / Drive link",
      "Brief or reference for each reel",
      "Final copy, script or key talking points where applicable",
      "Logo, brand colours and fonts",
      "Any mandatory text / claims / CTA",
      "Preferred order or priority of videos",
    ],
    addOns: [
      "Additional reel: quoted separately",
      "Advanced motion graphics / VFX: quoted separately",
      "16:9 / 1:1 adaptation: quoted separately",
      "Thumbnail / cover design: quoted separately",
      "Raw project files: quoted separately",
      "Express turnaround: subject to availability",
      "Add an adaptation / alternate cut or aspect-ratio version: quoted separately",
    ],
    terms: [
      "100% advance payment is required to begin work. Client must provide all footage, logos, brand assets and final copy in usable quality.",
      "The pack includes 1 revision per reel within the approved edit direction. New footage, a new edit direction, major restructuring, additional versions or changes after final approval are additional scope and may be charged separately. Licensed music/stock is subject to its third-party licence. Raw project files and working files are not included unless specifically agreed.",
      "Delivery timing starts after all required footage and inputs are received.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    cta: "buy",
  },
  {
    vertical: "studios",
    index: "02",
    name: "Founder / CEO Video Shoot",
    price: 44999,
    pitch: "Film a polished founder, CEO or spokesperson video with a professional on-location setup, ideal for thought leadership, explainers, announcements and brand communication.",
    audience: "Founders, CEOs, senior leaders, doctors, advocates, consultants, experts and spokespersons who need a professional camera-led video.",
    audienceTags: ["Founders", "CEOs", "Senior leaders", "Doctors", "Advocates", "Consultants", "Experts", "Spokespersons"],
    audienceNeed: "who need a professional camera-led video.",
    includes: [
      "Pre-shoot planning & styling references",
      "1 Professional camera setup",
      "2-point soft lighting",
      "Lapel microphone",
      "Videographer + assistant",
      "1 on-location shoot session",
      "7 final edited videos",
      "Up to 30 sec each",
      "Audio clean-up",
      "Colour correction",
      "Basic graphics & supers",
      "1080p final delivery",
    ],
    process: [
      "Purchase",
      "Confirm brief + shoot date",
      "We shoot + edit 7 videos",
      "Review & receive final exports",
    ],
    requirements: [
      "Approved script or talking points",
      "Confirmed shoot date and location",
      "Location access / permission",
      "Brand guidelines, logo and supers / name details",
      "Any presentation, product or visual assets to be shown",
      "One point of contact for shoot coordination and approvals",
    ],
    addOns: [
      "Additional camera + cinematographer, Still camera setup: ₹19,999/-",
      "Additional camera + cinematographer, Gimbal setup: ₹24,999/-",
      "Teleprompter: quoted separately",
      "Studio / paid location: at actuals + coordination",
      "Hair & makeup: at actuals",
      "Additional cutdowns / reels: quoted separately",
      "Additional shoot time: quoted separately",
      "Travel outside Mumbai / Navi Mumbai / Thane: quoted separately",
      "Add an adaptation / alternate cut or social version: quoted separately",
    ],
    terms: [
      "Shoot is currently available in Mumbai, Navi Mumbai and Thane and is subject to crew availability. Client is responsible for location access/permissions and timely approvals. Talent, studio/location fees, hair & makeup, props, set build, travel outside the included area and other third-party costs are excluded unless listed.",
      "Shoot rescheduling/cancellation follows the Website Cancellation & Refund Policy. Third-party costs already committed are non-refundable. The listed final edited video is included; raw footage/project files are not included unless agreed in writing. Additional edits, versions or scope changes are quoted separately.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    inPerson: true,
    cta: "buy",
  },
  {
    vertical: "studios",
    index: "03",
    name: "Half-Day Content Shoot",
    price: 59999,
    pitch: "Capture a bank of branded content in one focused half-day shoot, giving you multiple short-form videos and photographs from a single production day.",
    audience: "Founders, businesses, personal brands, product teams and marketing teams that want a month’s worth of content from one efficient shoot.",
    audienceTags: ["Founders", "Businesses", "Personal brands", "Product teams", "Marketing teams"],
    audienceNeed: "that want a month’s worth of content from one efficient shoot.",
    includes: [
      "Up to 5-hour shoot",
      "1 Professional camera setup",
      "1 location",
      "Content & shoot planning",
      "Up to 4 short-form videos",
      "10 edited photographs",
      "Basic lighting & professional audio",
      "Video editing",
      "Captions & branding",
      "9:16 or 16:9 master in 1080p",
    ],
    process: [
      "Purchase",
      "Plan content + confirm shoot",
      "We shoot for up to 5 hours",
      "We edit & deliver your content bank",
    ],
    requirements: [
      "Content objectives and priority topics",
      "Scripts / talking points or product information",
      "Confirmed location and permissions",
      "Talent / spokesperson availability",
      "Products, props or presentation assets required on camera",
      "Brand guidelines, logo and visual references",
      "One point of contact for shoot-day approvals",
    ],
    addOns: [
      "Second camera setup: quoted separately",
      "Additional reel / video: quoted separately",
      "Additional edited photographs: quoted separately",
      "Studio / paid location: at actuals + coordination",
      "Teleprompter: quoted separately",
      "Hair & makeup: at actuals",
      "Additional shoot hour: quoted separately",
      "Travel outside Mumbai / Navi Mumbai / Thane: quoted separately",
      "Extra adaptation / alternate aspect-ratio version: quoted separately",
    ],
    terms: [
      "Shoot is currently available in Mumbai, Navi Mumbai and Thane and is subject to crew availability. The 5-hour window begins at the confirmed call time; delays caused by the client/location may reduce usable shoot time. Client is responsible for location access/permissions, products, talent and brand inputs unless specifically included.",
      "Rescheduling/cancellation follows the Website Cancellation & Refund Policy. Third-party costs already committed are non-refundable. Additional shoot time, locations, deliverables, raw footage/project files or edit scope beyond the listed package are quoted separately.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    inPerson: true,
    cta: "buy",
  },
  {
    vertical: "studios",
    index: "04",
    name: "Event Content Coverage",
    price: 74999,
    pitch: "Capture the key moments, people and energy of your event through professional video and candid photography, then turn it into a polished branded aftermovie.",
    audience: "Corporate events, conferences, launches, networking events, awards, community events, brand activations and business gatherings.",
    audienceTags: ["Corporate events", "Conferences", "Launches", "Networking events", "Awards", "Community events", "Brand activations", "Business gatherings"],
    includes: [
      "Up to 4 hours of coverage",
      "2 professional cameras on gimbals",
      "Video coverage",
      "Candid event photography",
      "Stage / speaker moments",
      "Audience reactions",
      "Guest interactions",
      "1 branded event aftermovie",
      "25 edited high-resolution photographs",
      "Basic colour correction",
      "Music & branded edit",
      "9:16 or 16:9 master in 1080p",
    ],
    process: [
      "Purchase",
      "Share event brief + run of show",
      "We cover the event",
      "We edit & deliver aftermovie + photos",
    ],
    requirements: [
      "Event date, venue and confirmed access",
      "Run of show / event schedule",
      "List of key speakers, guests and priority moments",
      "Brand guidelines, logo and event artwork",
      "Venue / organiser permissions",
      "Any mandatory shots, sponsor branding or CTA",
      "On-ground event point of contact",
    ],
    addOns: [
      "Additional coverage hour: quoted separately",
      "Additional photographer / videographer: quoted separately",
      "Same-day / next-day reel: quoted separately",
      "Additional aftermovie / cutdowns: quoted separately",
      "Extra adaptation / alternate aspect-ratio version: quoted separately",
      "4K resolution shoot upgrade: ₹75,000/-",
      "Drone coverage: subject to venue / legal permissions",
      "Raw footage: quoted separately",
      "Travel outside Mumbai / Navi Mumbai / Thane: quoted separately",
    ],
    terms: [
      "Coverage is currently available in Mumbai, Navi Mumbai and Thane and is subject to crew availability. The 4-hour coverage window begins at the confirmed call time. Client must provide event schedule, venue access/permissions, key moments and branding requirements before the event.",
      "Rescheduling/cancellation follows the Website Cancellation & Refund Policy. Third-party costs already committed are non-refundable. Extra coverage hours, additional photographers/videographers, travel, live delivery, raw footage/project files or extra deliverables are quoted separately.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    inPerson: true,
    cta: "buy",
  },
  /* ------------------------------------------------------------ Brand & Design */
  {
    vertical: "brand-design",
    index: "01",
    name: "Logo Refresh",
    price: 24999,
    pitch: "Modernise an existing logo and visual identity without rebuilding your entire brand from scratch.",
    audience: "Existing businesses, startups and personal brands with a dated, inconsistent or hard-to-use logo that needs a more polished system.",
    audienceTags: ["Existing businesses", "Startups", "Personal brands"],
    audienceNeed: "with a dated, inconsistent or hard-to-use logo that needs a more polished system.",
    includes: [
      "Existing logo review",
      "Creative direction",
      "4 logo concepts / options presented",
      "4 logo mockups presented",
      "2 logo iterations",
      "Colour refinement",
      "Typography refinement",
      "Final primary logo",
      "Secondary logo variation",
      "PNG / JPG / SVG / PDF exports",
    ],
    process: [
      "Purchase",
      "Share current logo + brief",
      "We refine the identity",
      "Review & receive final logo files",
    ],
    requirements: [
      "Existing logo files, preferably vector / high resolution",
      "Business and brand context",
      "Reason for the refresh / current logo pain points",
      "Competitor or category references",
      "Where the logo will be used",
      "Preferred / restricted colours or visual elements",
      "One decision maker for consolidated feedback",
    ],
    addOns: [
      "Additional logo revision after the 2 included iterations: quoted separately",
      "Mini brand guidelines: quoted separately",
      "Additional logo routes: quoted separately",
      "Stationery / collateral design: quoted separately",
      "Social media brand kit: quoted separately",
      "Motion logo / animated ident: quoted separately",
      "Brand strategy / positioning: quoted separately",
      "Add an adaptation / extra logo application or format: quoted separately",
    ],
    terms: [
      "100% advance payment is required to begin work. The existing logo, business context and required brand references must be supplied before design starts.",
      "The package includes 2 logo iterations. Across the included process, 4 logo concepts / options will be presented with 4 mockup applications for review. Feedback must be consolidated at each iteration.",
      "Revisions requested after the 2 included iterations, a completely new creative direction after approval, additional logo routes, extra collateral or other scope changes are chargeable and quoted separately.",
      "Final exports listed in the package are included; editable source / working files are not included unless specifically agreed. Fonts, stock and other third-party assets remain subject to their respective licences.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    cta: "buy",
  },
  {
    vertical: "brand-design",
    index: "02",
    name: "Campaign Creative Kit",
    price: 29999,
    pitch: "Build the core visual system for one campaign so every creative feels connected, recognisable and ready to extend across digital channels.",
    audience: "Marketing teams, startups, D2C brands, event teams and agencies launching a campaign, offer, product, announcement or seasonal communication.",
    audienceTags: ["Marketing teams", "Startups", "D2C brands", "Event teams", "Agencies"],
    audienceNeed: "launching a campaign, offer, product, announcement or seasonal communication.",
    includes: [
      "1 Campaign Key Visual",
      "Campaign visual direction",
      "7 campaign creatives",
      "Brand typography & colour styling",
      "Up to 3 selected adaptations",
      "Social-ready exports",
      "2 consolidated revision rounds per creative",
    ],
    process: [
      "Purchase",
      "Share campaign brief + assets",
      "We build 1 Key Visual + 7 creatives",
      "Review & receive final exports",
    ],
    requirements: [
      "Campaign brief and objective",
      "Final copy, offer and CTA",
      "Brand guidelines and logo files",
      "Product images / packshots / required assets",
      "Mandatory disclaimers or partner logos",
      "Required platforms and sizes",
      "Visual references / competitor examples if available",
    ],
    addOns: [
      "Campaign Expansion Add-on: 1 additional Key Visual + 7 additional campaign creatives, quoted separately",
      "Additional creative: quoted separately",
      "Additional adaptation / platform size: quoted separately",
      "Motion version of Key Visual: quoted separately",
      "Performance ad variants: quoted separately",
      "Language adaptations: quoted separately",
      "Custom illustration / 3D: quoted separately",
    ],
    terms: [
      "100% advance payment is required to begin work. Client must provide the final campaign brief, copy, mandatory brand elements and claims before design starts.",
      "2 consolidated revision rounds are included within the approved key visual/direction. New concepts, additional key visuals, extra formats/adaptations or major copy changes after approval are additional scope and may affect timeline/cost. Final social-ready exports listed in the package are included; working/source files are not included unless agreed.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    cta: "buy",
  },
  {
    vertical: "brand-design",
    index: "03",
    name: "Pitch Deck Makeover",
    price: 32999,
    pitch: "Turn your existing presentation content into a structured, polished and on-brand deck that is easier to understand, present and sell from.",
    audience: "Founders, sales teams, agencies, consultants and businesses preparing investor decks, pitch decks, credentials, sales presentations or internal presentations.",
    audienceTags: ["Founders", "Sales teams", "Agencies", "Consultants", "Businesses"],
    audienceNeed: "preparing investor decks, pitch decks, credentials, sales presentations or internal presentations.",
    includes: [
      "Up to 22 slides",
      "Presentation design direction",
      "Complete layout redesign",
      "Typography styling",
      "Colour system",
      "Charts / infographic styling",
      "Image treatment",
      "Editable final presentation",
      "PDF export",
      "2 consolidated revision rounds",
    ],
    process: [
      "Purchase",
      "Upload deck + final copy",
      "We redesign up to 22 slides",
      "Review & receive editable deck + PDF",
    ],
    requirements: [
      "Final or near-final presentation copy",
      "Existing PPT / Google Slides / document",
      "Brand guidelines, logo and fonts",
      "Data, charts and source information",
      "Images / case-study assets where applicable",
      "Reference decks or preferred style",
      "One point of contact for consolidated feedback",
    ],
    addOns: [
      "Additional slides: quoted separately",
      "Content rewriting / storytelling: quoted separately",
      "Advanced data visualisation: quoted separately",
      "Custom illustration / iconography: quoted separately",
      "Presentation animation: quoted separately",
      "Speaker notes / presentation script: quoted separately",
      "Add an adaptation / alternate deck version or format: quoted separately",
    ],
    terms: [
      "100% advance payment is required to begin work. Client must provide final/near-final copy, data, brand assets and references before layout production begins.",
      "2 consolidated revision rounds are included within the approved presentation direction. Major content rewrites, new slides beyond the included 15, new data visualisations or a complete change of direction are additional scope. An editable final presentation and PDF are included; external fonts, stock assets or third-party licences remain subject to their own terms.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    cta: "buy",
  },
  {
    vertical: "brand-design",
    index: "04",
    name: "Marketing Launch Kit",
    price: 39999,
    pitch: "Create the essential visual assets needed to launch one product, service or campaign across social, email and digital touchpoints.",
    audience: "Startups, D2C brands, marketing teams and businesses preparing a new product launch, campaign launch, offer or announcement.",
    audienceTags: ["Startups", "D2C brands", "Marketing teams", "Businesses"],
    audienceNeed: "preparing a new product launch, campaign launch, offer or announcement.",
    includes: [
      "4 Hero Key Visuals",
      "15 social creatives",
      "2 story adaptations",
      "1 digital banner",
      "2 email / mailer creatives",
      "Campaign design system",
      "Brand styling",
      "Ready-to-publish exports",
      "2 consolidated revision rounds",
    ],
    process: [
      "Purchase",
      "Share launch brief + assets",
      "We build the launch creative system",
      "Review & receive ready-to-publish assets",
    ],
    requirements: [
      "Launch / campaign brief",
      "Final copy, offer and CTA",
      "Brand guidelines, logo and fonts",
      "Product images / packshots / screenshots",
      "Mandatory claims, disclaimers or partner logos",
      "Required launch date and channels",
      "Reference visuals / competitor examples if available",
    ],
    addOns: [
      "Motion Key Visual: quoted separately",
      "Additional social creatives: quoted separately",
      "Additional platform adaptations: quoted separately",
      "Performance creative variants: quoted separately",
      "Landing page design: quoted separately",
      "Language adaptations: quoted separately",
      "Add an adaptation / extra platform size or version: quoted separately",
    ],
    terms: [
      "100% advance payment is required to begin work. Client must provide the approved campaign/product brief, final copy, brand assets, mandatory claims and references before design begins.",
      "2 consolidated revision rounds are included within the approved launch direction. New concepts, additional formats, extra creatives, major copy changes or changes after final approval are additional scope and may affect cost/timeline. Final ready-to-publish exports listed in the package are included; source/working files are not included unless agreed.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    cta: "buy",
  },
  {
    vertical: "brand-design",
    index: "05",
    name: "Brand Build",
    priceLabel: "From ₹1,49,999/- + GST",
    pitch: "Build a complete brand identity system from strategy to visual execution, designed for businesses launching, repositioning or upgrading how the brand looks, sounds and communicates.",
    audience: "New businesses, funded startups, growing brands and existing companies going through a serious rebrand or repositioning.",
    audienceTags: ["New businesses", "Funded startups", "Growing brands", "Existing companies"],
    audienceNeed: "going through a serious rebrand or repositioning.",
    includes: [
      "Brand discovery & direction",
      "Brand strategy & positioning",
      "Brand personality / voice direction",
      "Brand guidelines",
      "Visual identity & logo system",
      "Colour & typography system",
      "Brand Collaterals:",
      "1 Visiting Card",
      "1 Letterhead",
      "1 Envelope",
      "1 Email Signature",
      "Selected launch applications agreed at kickoff",
      "2 consolidated identity revision rounds",
    ],
    process: [
      "Book a discovery call",
      "Discovery + brand strategy",
      "We build the identity system",
      "Review & receive guidelines + brand assets",
    ],
    requirements: [
      "Founder / leadership discovery inputs",
      "Business goals and offering",
      "Target audience and market",
      "Competitor references",
      "Existing brand assets, research or previous identity where applicable",
      "Preferred / restricted names, colours or visual directions",
      "One final decision maker for consolidated approvals",
    ],
    addOns: [
      "Brand naming / tagline: quoted separately",
      "Packaging design: quoted separately",
      "Website UI / landing page design: quoted separately",
      "Social launch kit: quoted separately",
      "Motion identity / brand film: quoted separately",
      "Additional collateral: quoted separately",
      "Printing / production: at actuals",
      "Add an adaptation / additional brand application or collateral version: quoted separately",
    ],
    note: "Typical timeline: 3–4 weeks. 2 consolidated identity revision rounds.",
    terms: [
      "This is a quoted project. Final scope, price, payment schedule, milestones and delivery dates are confirmed in the written quotation before work begins.",
      "The package includes 2 consolidated identity revision rounds. A new strategic/creative direction after approval, additional naming/strategy work, extra collateral, extensive copywriting, printing/production or third-party costs are outside the base scope unless quoted. Final brand assets are handed over after full payment; Genesis pre-existing tools, templates and working files remain excluded unless agreed.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    cta: "call",
  },
  /* ------------------------------------------------------------ Influence */
  {
    vertical: "influence",
    index: "01",
    name: "UGC Starter Pack",
    price: 39999,
    pitch: "Create 4 natural, creator-style UGC videos that feel native to social feeds and are ready for organic content or paid-social testing.",
    audience: "D2C brands, apps, services, startups and consumer businesses that want authentic creator-led content without running a full influencer campaign.",
    audienceTags: ["D2C brands", "Apps", "Services", "Startups", "Consumer businesses"],
    audienceNeed: "that want authentic creator-led content without running a full influencer campaign.",
    includes: [
      "4 UGC videos",
      "1 Creator",
      "Phone-shot production",
      "Brief & scripting support",
      "Product / service integration",
      "Standard video editing",
      "Basic music & sound",
      "9:16 or 16:9 delivery in 1080p",
      "1 revision per video",
    ],
    process: [
      "Purchase",
      "Share brief + ship product",
      "1 creator produces 4 UGC videos",
      "Review & receive social-ready UGC",
    ],
    requirements: [
      "Product / service brief and USP",
      "Target audience",
      "Key messages, claims and do / don’t guidelines",
      "Brand guidelines / logo if required on-screen",
      "Reference UGC videos or preferred style",
      "Physical product shipped to creator in time, where applicable",
      "Required usage / platform information",
    ],
    addOns: [
      "Additional UGC Video: ₹19,000/- per video",
      "Additional UGC Creator: ₹11,999/- per creator",
      "Extra hook / opening variations: quoted separately",
      "Raw creator footage: quoted separately",
      "Whitelisting / creator-handle usage: quoted separately",
      "Extended paid usage / exclusivity: quoted separately",
      "Express delivery: subject to creator availability",
      "Add an adaptation / alternate UGC cut or platform version: quoted separately",
    ],
    note: "No influencer posting included.",
    terms: [
      "100% advance payment is required to begin production. Client must provide the product/service information, brand guidelines, mandatory claims and any physical product required for filming in time for production.",
      "1 revision per video is included within the approved brief. Reshoots, new concepts/scripts, additional hooks/versions or changes caused by a changed brief are additional scope. Influencer/creator posting is not included. The included UGC is for the client’s owned channels and paid social; any special usage, whitelisting, exclusivity or creator-specific rights must be agreed separately where applicable.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    cta: "buy",
  },
  {
    vertical: "influence",
    index: "02",
    name: "UGC Performance Pack",
    price: 64999,
    pitch: "Create 10 performance-focused UGC videos across 3 creators, hooks and angles, giving your brand a larger bank of polished creative variations to test across paid and organic social.",
    audience: "Brands actively running Meta, Instagram, YouTube Shorts or other paid-social campaigns that need multiple creator faces, messages and performance angles.",
    audienceTags: ["Brands"],
    audienceNeed: "actively running Meta, Instagram, YouTube Shorts or other paid-social campaigns that need multiple creator faces, messages and performance angles.",
    includes: [
      "10 UGC videos",
      "3 Creators",
      "Professional camera production",
      "Creator coordination",
      "Multiple content hooks & angles",
      "Scripting",
      "Product / service integration",
      "Advanced video editing",
      "Captions & supers",
      "Music & sound treatment",
      "Paid-social-ready exports",
      "9:16 delivery in 1080p",
      "1 revision per video",
    ],
    process: [
      "Purchase",
      "Share campaign brief + ship products",
      "3 creators produce 10 UGC videos",
      "Review & receive paid-social-ready assets",
    ],
    requirements: [
      "Campaign / product brief and USP",
      "Target audience and performance objective",
      "Key claims, mandatory talking points and do / don’t guidelines",
      "Brand guidelines and visual assets",
      "Reference ads / UGC examples",
      "Physical products shipped to creators in time, where applicable",
      "Usage requirements and campaign dates",
    ],
    addOns: [
      "Additional UGC Video: ₹19,000/- per video",
      "Additional UGC Creator: ₹11,999/- per creator",
      "Extra hook / CTA cutdowns: quoted separately",
      "Raw creator footage: quoted separately",
      "Whitelisting / creator-handle usage: quoted separately",
      "Extended paid usage / exclusivity: quoted separately",
      "Additional platform adaptations: quoted separately",
      "Add an adaptation / alternate UGC cut or platform version: quoted separately",
    ],
    note: "No influencer posting included.",
    terms: [
      "100% advance payment is required to begin production. Client must provide the product/service information, brand guidelines, mandatory claims and any physical product required for filming in time for production.",
      "1 revision per video is included within the approved brief. Reshoots, new concepts/scripts, additional hooks/versions or changes caused by a changed brief are additional scope. Influencer/creator posting is not included. The included UGC is for the client’s owned channels and paid social; any special usage, whitelisting, exclusivity or creator-specific rights must be agreed separately where applicable.",
      "Creator availability may affect scheduling; any material change in creator requirement can affect cost/timeline.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    cta: "buy",
  },
  {
    vertical: "influence",
    index: "03",
    name: "Influencer Campaign Management",
    priceLabel: "15% Agency Commission + Creator Fees",
    pitch: "Run an end-to-end influencer campaign with Genesis managing the process from strategy and creator discovery through negotiation, execution, posting and reporting.",
    audience: "Brands, agencies and marketing teams running influencer launches, awareness campaigns, product pushes, event amplification or always-on creator programs.",
    audienceTags: ["Brands", "Agencies", "Marketing teams"],
    audienceNeed: "running influencer launches, awareness campaigns, product pushes, event amplification or always-on creator programs.",
    includes: [
      "Campaign strategy",
      "Creator discovery",
      "Creator verification",
      "Shortlisting",
      "Creator outreach",
      "Rate negotiation",
      "Briefing",
      "Content coordination",
      "Approval management",
      "Posting coordination",
      "Campaign tracking",
      "Final campaign report",
    ],
    process: [
      "Book a campaign call",
      "Share objective + budget",
      "We shortlist, negotiate & execute",
      "Track, publish & report",
    ],
    requirements: [
      "Campaign objective and KPI",
      "Total creator / campaign budget",
      "Target audience, geography and platforms",
      "Preferred creator categories / audience size",
      "Deliverables and campaign dates",
      "Brand guidelines, key messages and mandatory claims",
      "Usage rights / exclusivity requirements",
      "One approval point of contact",
    ],
    addOns: [
      "Creator fees: separate, based on final shortlist",
      "Paid media / boosting: quoted separately",
      "Whitelisting / creator-handle usage: quoted separately",
      "Exclusivity / extended usage rights: quoted separately",
      "On-ground event / creator attendance: quoted separately",
      "Product logistics / seeding: quoted separately",
      "Additional content production: quoted separately",
      "Add an adaptation / additional platform deliverable: quoted separately",
    ],
    note: "Creator fees are separate and depend on the creators selected, deliverables, platform and usage rights.",
    terms: [
      "This service is quoted at 15% agency commission + creator fees. Creator fees are separate and are confirmed based on the final shortlist, deliverables, platform, usage rights, exclusivity and campaign requirements before booking.",
      "Creator availability and rates remain subject to confirmation until booked. Any paid usage rights, whitelisting, exclusivity, travel, production, boosting/media spend or additional deliverables are separate unless specifically included in the written quotation. Client approvals must be provided on time; changes after creator confirmation or content approval may affect cost and timeline.",
      "Final payment schedule, creator cancellation terms and campaign-specific conditions are confirmed in the written quotation.",
      "Full Website Terms & Cancellation & Refund Policy apply.",
    ],
    cta: "call",
  },
];

export const productsFor = (vertical: VerticalKey) => products.filter((product) => product.vertical === vertical);

/** The lowest one-time price on the site — what "from" means for one-time work. */
export const lowestProductPrice = Math.min(...products.flatMap((product) => (product.price ? [product.price] : [])));
